# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f1daef32f7052115a100cdb78ecdf791"
name = "CustomScale-app"
application_url = "https://highquality.allgovjobs.com"
embedded = true
handle = "customscale-app"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/backend/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [ "https://highquality.allgovjobs.com/backend/auth/callback" ]

[app_proxy]
url = "https://highquality.allgovjobs.com/api"
subpath = "customscale-app"
prefix = "apps"
