import { useMemo, useState } from "react";
import { useFetcher } from "react-router";
import { boundary } from "@shopify/shopify-app-react-router/server";
import { authenticate } from "../shopify.server";
import { generateTransferSheetsByProduct } from "../orderMetafieldApi.server";

export const loader = async ({ request }) => {
  // Sheets are generated by the action, not on page load — rendering them is
  // expensive and would re-run on every refresh.
  await authenticate.admin(request);
  return null;
};

/** Split the free-text field into a de-duped list of order IDs. */
function parseOrderIds(raw) {
  return [
    ...new Set(
      String(raw || "")
        .split(/[\s,]+/)
        .map((id) => id.trim())
        .filter(Boolean),
    ),
  ];
}

export const action = async ({ request }) => {
  const { session } = await authenticate.admin(request);
  const form = await request.formData();
  const orderIds = parseOrderIds(form.get("orderIds"));

  if (!orderIds.length) {
    return { ok: false, orders: [], error: "Enter at least one order ID." };
  }

  try {
    const res = await generateTransferSheetsByProduct({
      shop: session.shop,
      orderIds,
    });

    if (!res.ok) {
      const text = await res.text();
      return {
        ok: false,
        orders: [],
        error: `API returned ${res.status}: ${text.slice(0, 200)}`,
      };
    }

    const data = await res.json().catch(() => null);
    const orders = Array.isArray(data?.orders) ? data.orders : [];

    if (!orders.length) {
      return {
        ok: false,
        orders: [],
        error: data?.error || "The service returned no results for these orders.",
      };
    }

    // The API reports success: true even when every order failed, so the real
    // outcome has to come from the per-order entries.
    return { ok: true, orders, error: null };
  } catch (err) {
    console.error("[app.orders] transfer sheet generation failed:", err);
    return {
      ok: false,
      orders: [],
      error: err.message || "Failed to reach the transfer sheet service.",
    };
  }
};

const PAGE_CSS = `
.ots-wrap { width: 100%; max-width: 100%; box-sizing: border-box; }
.ots-wrap *, .ots-wrap *::before, .ots-wrap *::after { box-sizing: border-box; }

.ots-card {
  background: #fff;
  border: 1px solid #e1e3e5;
  border-radius: 12px;
  padding: 20px;
  box-shadow: 0 1px 0 rgba(22,29,37,0.04);
  margin-bottom: 20px;
  min-width: 0;
}
.ots-card-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 12px;
  margin-bottom: 16px;
  flex-wrap: wrap;
}
.ots-card-title { font-size: 16px; font-weight: 600; color: #202223; margin: 0; }
.ots-card-sub { font-size: 13px; color: #6d7175; margin-top: 2px; }

.ots-label {
  display: block;
  font-weight: 500;
  font-size: 13px;
  margin-bottom: 6px;
  color: #202223;
}
.ots-hint { font-size: 12px; color: #6d7175; margin-top: 6px; }
.ots-input {
  width: 100%;
  max-width: 480px;
  padding: 10px 14px;
  font-size: 14px;
  border: 1px solid #c9cccf;
  border-radius: 8px;
  outline: none;
  background: #fff;
  color: #202223;
  transition: border-color 0.15s, box-shadow 0.15s;
}
.ots-input:focus { border-color: #008060; box-shadow: 0 0 0 3px rgba(0,128,96,0.15); }

.ots-actions { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; margin-top: 20px; }

.ots-btn {
  padding: 9px 18px;
  font-size: 14px;
  font-weight: 600;
  border: 1px solid transparent;
  border-radius: 8px;
  cursor: pointer;
  text-decoration: none;
  display: inline-flex;
  align-items: center;
  gap: 8px;
  transition: opacity 0.15s, background 0.15s, border-color 0.15s;
}
.ots-btn[disabled] { opacity: 0.6; cursor: not-allowed; }
.ots-btn-primary { background: #008060; color: #fff; }
.ots-btn-primary:hover:not([disabled]) { background: #006e52; }
.ots-btn-secondary { background: #f6f6f7; color: #202223; border-color: #c9cccf; }
.ots-btn-secondary:hover:not([disabled]) { background: #ececed; }

.ots-btn-small {
  padding: 6px 12px;
  font-size: 13px;
  font-weight: 500;
  border-radius: 6px;
}

.ots-banner {
  padding: 12px 16px;
  border-radius: 10px;
  font-size: 14px;
  margin-bottom: 16px;
  display: flex;
  align-items: center;
  gap: 10px;
  flex-wrap: wrap;
}
.ots-banner-error { background: #fee2e2; border: 1px solid #fca5a5; color: #991b1b; }
.ots-banner-warn { background: #fef3c7; border: 1px solid #fcd34d; color: #92400e; }
.ots-banner-info { background: #eef4ff; border: 1px solid #b9cdf5; color: #1f3f80; }

.ots-badge {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 3px 10px;
  font-size: 12px;
  font-weight: 600;
  border-radius: 999px;
  background: #e3f1df;
  color: #0c5132;
  white-space: nowrap;
}
.ots-badge-neutral { background: #f1f2f3; color: #414f3e; }
.ots-badge-warn { background: #fdf1ef; color: #b8200a; }

.ots-order {
  border: 1px solid #e1e3e5;
  border-radius: 12px;
  margin-bottom: 16px;
  overflow: hidden;
  background: #fff;
}
.ots-order-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  flex-wrap: wrap;
  padding: 14px 18px;
  background: #fafbfb;
  border-bottom: 1px solid #e1e3e5;
}
.ots-order-name { font-size: 15px; font-weight: 600; color: #202223; }
.ots-order-meta { font-size: 12px; color: #6d7175; margin-top: 2px; }
.ots-order-body { padding: 6px 18px 18px; }

.ots-sheet {
  border-bottom: 1px solid #f1f2f3;
  padding: 16px 0;
  display: flex;
  gap: 16px;
  justify-content: space-between;
  flex-wrap: wrap;
}
.ots-sheet:last-child { border-bottom: none; }
.ots-sheet-info { min-width: 0; flex: 1 1 260px; }
.ots-sheet-title { font-size: 14px; font-weight: 600; color: #202223; }
.ots-sheet-meta { font-size: 13px; color: #6d7175; margin-top: 4px; }
.ots-sheet-actions { display: flex; align-items: flex-start; gap: 8px; flex-wrap: wrap; }

.ots-mono {
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  background: #f1f2f3;
  padding: 2px 7px;
  border-radius: 6px;
  font-size: 12px;
  white-space: nowrap;
}

.ots-breakdown {
  width: 100%;
  max-width: 360px;
  border-collapse: separate;
  border-spacing: 0;
  margin-top: 10px;
  font-size: 13px;
  border: 1px solid #e1e3e5;
  border-radius: 8px;
  overflow: hidden;
}
.ots-breakdown th {
  text-align: left;
  padding: 7px 12px;
  background: #fafbfb;
  border-bottom: 1px solid #e1e3e5;
  font-weight: 600;
  color: #414f3e;
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}
.ots-breakdown td {
  padding: 7px 12px;
  border-bottom: 1px solid #f1f2f3;
  color: #202223;
}
.ots-breakdown tr:last-child td { border-bottom: none; }

.ots-empty {
  padding: 48px 24px;
  text-align: center;
  color: #6d7175;
  border: 1px dashed #c9cccf;
  border-radius: 12px;
  background: #fafbfb;
}
.ots-empty-title { font-size: 16px; font-weight: 600; color: #202223; margin-bottom: 6px; }

.ots-spinner {
  width: 14px;
  height: 14px;
  border: 2px solid rgba(255,255,255,0.45);
  border-top-color: #fff;
  border-radius: 50%;
  animation: ots-spin 0.7s linear infinite;
}
@keyframes ots-spin { to { transform: rotate(360deg); } }

@media (max-width: 720px) {
  .ots-card { padding: 16px; }
  .ots-input { max-width: 100%; }
  .ots-actions .ots-btn { flex: 1 1 auto; justify-content: center; }
  .ots-sheet-actions { width: 100%; }
}
`;

/** Same-origin proxy download so the browser saves the file instead of opening it. */
function downloadHref(sheet) {
  return sheet.pngFileName
    ? `/app/orders/download?file=${encodeURIComponent(sheet.pngFileName)}`
    : sheet.downloadUrl || null;
}

function sheetLabel(sheet) {
  const title = sheet.productTitle || "Transfer sheet";
  return sheet.partCount > 1
    ? `${title} (Sheet ${sheet.partIndex} of ${sheet.partCount})`
    : title;
}

function sheetSize(sheet) {
  const dims = sheet.sheetDimensions;
  return dims ? `${dims.widthIn}" × ${dims.heightIn}"` : "Size unavailable";
}

export default function OrdersPage() {
  const fetcher = useFetcher();
  const [orderIdInput, setOrderIdInput] = useState("");

  const isGenerating = fetcher.state !== "idle";
  const result = fetcher.data;
  const orders = useMemo(() => result?.orders || [], [result]);

  const parsedIds = useMemo(() => parseOrderIds(orderIdInput), [orderIdInput]);

  const summary = useMemo(() => {
    const ready = orders.filter((o) => o.success);
    return {
      ready: ready.length,
      failed: orders.length - ready.length,
      sheets: ready.reduce((n, o) => n + (o.sheets?.length || 0), 0),
    };
  }, [orders]);

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!parsedIds.length) return;
    const fd = new FormData();
    fd.set("orderIds", parsedIds.join(","));
    fetcher.submit(fd, { method: "post" });
  };

  // Downloads are triggered one at a time; browsers drop simultaneous ones.
  const downloadAll = (sheets) => {
    sheets
      .map(downloadHref)
      .filter(Boolean)
      .forEach((href, i) => {
        setTimeout(() => {
          const a = document.createElement("a");
          a.href = href;
          a.download = "";
          document.body.appendChild(a);
          a.click();
          a.remove();
        }, i * 400);
      });
  };

  return (
    <s-page heading="Transfer sheets">
      <s-section>
        <s-box padding="base">
          <style>{PAGE_CSS}</style>
          <div className="ots-wrap">
            <div className="ots-card">
              <div className="ots-card-header">
                <div>
                  <h3 className="ots-card-title">Generate transfer sheets</h3>
                  <div className="ots-card-sub">
                    Designs are grouped by product and packed onto 22.5&quot;
                    wide sheets at 300 DPI.
                  </div>
                </div>
              </div>

              <form onSubmit={handleSubmit}>
                <label className="ots-label" htmlFor="order-ids">
                  Order ID
                </label>
                <input
                  id="order-ids"
                  type="text"
                  value={orderIdInput}
                  onChange={(e) => setOrderIdInput(e.target.value)}
                  placeholder="e.g. 6103847291"
                  className="ots-input"
                  disabled={isGenerating}
                  autoComplete="off"
                />
                <div className="ots-hint">
                  Numeric order ID from the Shopify admin URL. Separate multiple
                  IDs with a comma or space
                  {parsedIds.length > 1 ? ` — ${parsedIds.length} detected` : ""}
                  .
                </div>

                <div className="ots-actions">
                  <button
                    type="submit"
                    className="ots-btn ots-btn-primary"
                    disabled={isGenerating || !parsedIds.length}
                  >
                    {isGenerating && <span className="ots-spinner" />}
                    {isGenerating ? "Generating…" : "Generate sheets"}
                  </button>
                  {orderIdInput && !isGenerating && (
                    <button
                      type="button"
                      className="ots-btn ots-btn-secondary"
                      onClick={() => setOrderIdInput("")}
                    >
                      Clear
                    </button>
                  )}
                </div>
              </form>
            </div>

            {isGenerating && (
              <div className="ots-banner ots-banner-info">
                <span style={{ fontWeight: 700 }}>Working</span>
                <span>
                  Rendering sheets for {parsedIds.length}{" "}
                  {parsedIds.length === 1 ? "order" : "orders"}. This can take
                  tens of seconds per order — keep this tab open.
                </span>
              </div>
            )}

            {result?.error && (
              <div className="ots-banner ots-banner-error">
                <span style={{ fontWeight: 700 }}>Error</span>
                <span>{result.error}</span>
              </div>
            )}

            {!isGenerating && orders.length > 0 && (
              <>
                {summary.ready === 0 ? (
                  <div className="ots-banner ots-banner-warn">
                    <span style={{ fontWeight: 700 }}>No sheets</span>
                    <span>
                      None of the {orders.length}{" "}
                      {orders.length === 1 ? "order" : "orders"} produced a
                      transfer sheet. See the details below.
                    </span>
                  </div>
                ) : (
                  <div className="ots-banner ots-banner-info">
                    <span style={{ fontWeight: 700 }}>Ready</span>
                    <span>
                      {summary.sheets}{" "}
                      {summary.sheets === 1 ? "sheet" : "sheets"} across{" "}
                      {summary.ready}{" "}
                      {summary.ready === 1 ? "order" : "orders"}
                      {summary.failed > 0
                        ? ` — ${summary.failed} could not be generated`
                        : ""}
                      .
                    </span>
                  </div>
                )}

                {orders.map((order) => {
                  const sheets = order.sheets || [];
                  return (
                    <div className="ots-order" key={order.orderId}>
                      <div className="ots-order-head">
                        <div>
                          <div className="ots-order-name">
                            {order.orderName || `Order ${order.orderId}`}
                          </div>
                          <div className="ots-order-meta">
                            ID {order.orderId}
                            {order.success
                              ? ` · ${order.totalDesigns} design${
                                  order.totalDesigns === 1 ? "" : "s"
                                } · ${sheets.length} sheet${
                                  sheets.length === 1 ? "" : "s"
                                }`
                              : ""}
                          </div>
                        </div>
                        {order.success ? (
                          <div className="ots-sheet-actions">
                            <span className="ots-badge">Ready</span>
                            {sheets.length > 1 && (
                              <button
                                type="button"
                                className="ots-btn ots-btn-small ots-btn-secondary"
                                onClick={() => downloadAll(sheets)}
                              >
                                Download all ({sheets.length})
                              </button>
                            )}
                          </div>
                        ) : (
                          <span
                            className={`ots-badge ${
                              order.skipped
                                ? "ots-badge-neutral"
                                : "ots-badge-warn"
                            }`}
                          >
                            {order.skipped ? "Skipped" : "Failed"}
                          </span>
                        )}
                      </div>

                      <div className="ots-order-body">
                        {!order.success && (
                          <p style={{ color: "#6d7175", fontSize: "13px" }}>
                            {order.message ||
                              (typeof order.error === "string"
                                ? order.error
                                : JSON.stringify(order.error)) ||
                              "No sheets were generated for this order."}
                          </p>
                        )}

                        {sheets.map((sheet) => {
                          const href = downloadHref(sheet);
                          return (
                            <div
                              className="ots-sheet"
                              key={sheet.pngFileName || `${sheet.productId}-${sheet.partIndex}`}
                            >
                              <div className="ots-sheet-info">
                                <div className="ots-sheet-title">
                                  {sheetLabel(sheet)}
                                </div>
                                <div className="ots-sheet-meta">
                                  {sheetSize(sheet)} · {sheet.totalDesigns}{" "}
                                  design{sheet.totalDesigns === 1 ? "" : "s"} ·
                                  Pre-cut: {sheet.preCut || "No"}
                                </div>
                                <div className="ots-sheet-meta">
                                  Product <span className="ots-mono">{sheet.productId}</span>
                                </div>

                                {sheet.designBreakdown?.length > 0 && (
                                  <table className="ots-breakdown">
                                    <thead>
                                      <tr>
                                        <th>Dimension</th>
                                        <th>Pre-cut</th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                      {sheet.designBreakdown.map((item, i) => (
                                        <tr key={`${item.dimension}-${i}`}>
                                          <td>
                                            {item.dimension}
                                            {item.count > 1
                                              ? ` (×${item.count})`
                                              : ""}
                                          </td>
                                          <td>{item.preCut}</td>
                                        </tr>
                                      ))}
                                    </tbody>
                                  </table>
                                )}
                              </div>

                              <div className="ots-sheet-actions">
                                {href ? (
                                  <a
                                    href={href}
                                    download
                                    className="ots-btn ots-btn-small ots-btn-primary"
                                  >
                                    Download
                                  </a>
                                ) : (
                                  <span className="ots-badge ots-badge-warn">
                                    Unavailable
                                  </span>
                                )}
                                {sheet.downloadUrl && (
                                  <a
                                    href={sheet.downloadUrl}
                                    target="_blank"
                                    rel="noreferrer"
                                    className="ots-btn ots-btn-small ots-btn-secondary"
                                  >
                                    Preview
                                  </a>
                                )}
                              </div>
                            </div>
                          );
                        })}
                      </div>
                    </div>
                  );
                })}
              </>
            )}

            {!isGenerating && !result && (
              <div className="ots-empty">
                <div className="ots-empty-title">No sheets generated yet</div>
                <div>
                  Enter an order ID above to build its transfer sheets and
                  download them.
                </div>
              </div>
            )}
          </div>
        </s-box>
      </s-section>

      <s-section slot="aside" heading="About">
        <s-paragraph>
          Enter an <strong>Order ID</strong> to generate print-ready transfer
          sheets. Only line items carrying a <strong>CustomImage</strong>{" "}
          property are included — orders without one are skipped.
        </s-paragraph>
        <s-paragraph>
          Sheets are grouped per product and split into parts when a sheet would
          run past 300&quot; in length. Generating does not send an email.
        </s-paragraph>
      </s-section>
    </s-page>
  );
}

export const headers = (headersArgs) => {
  return boundary.headers(headersArgs);
};
